### ISSUE TITLE
Error: Failed to connect before the deadline

### ISSUE THREAD

**Issue by MaxXx1313** [MaxXx1313/fabric-rest#5]
Sometimes we catch an error in a few seconds after start up the server: 
```
Error: Error: Error: Failed to connect before the deadline
    at checkState (/home/cenos/fabric-rest-dev/server/node_modules/grpc/src/client.js:838:16)
    at helper.getClientForOrg.then.then (/home/cenos/fabric-rest-dev/server/lib-fabric/query.js:373:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at helper.getClientForOrg.then.then.catch (/home/cenos/fabric-rest-dev/server/lib-fabric/query.js:376:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by bjzhang03** [comment]
I have the same problem when i use the fabric

**Comment by MaxXx1313** [comment]
When we updated to the latest fabric-client (v 1.2.1) the stack trace have changed:
```
error: [Remote.js]: Error: Failed to connect before the deadline
error: [Orderer.js]: Orderer grpcs://***.blockchain.ibm.com:20127 has an error Error: Failed to connect before the deadline
Request failed: POST /channels/someChannel/chaincodes/someChaincode: Failed to connect before the deadline
Error: Failed to connect before the deadline
    at checkState (/home/user/fabric-rest/server/node_modules/grpc/src/client.js:838:16)
Error: Failed to connect before the deadline
    at checkState (/home/user/fabric-rest/server/node_modules/grpc/src/client.js:838:16)
```
